### ISSUE TITLE
Button hover boxes messed up on clan creation screen

### ISSUE THREAD

**Issue by tailhaver** [tailhaver/clangen#4]
also button arrows are messed up

**Comment by larkgz** [comment]
More specifically, they're messed up on the name clan and cat choosing clan subscreens. 

In the name clan subscreen, hovering does not work at all. In the choose leader, choose deputy, etc. It's specifically the bottom parts of the button where hovering is broken. This issue may be related to the background illustrations.

EDIT: It's definitely related to the background illustrations. When I disabled them, hovering displayed properly again.

**Comment by larkgz** [comment]
Now that I'm testing on the main development branch, it seems like this hovering bug existed prior to the rewrite. In other screens, the issue is resolved by blitting backgrounds manually to `screen` in `on_use()`.

**Comment by tailhaver** [comment]
seems to be fixed with the latest build? closing unless it comes back up
